### PR TITLE
Fix 1, 2, 3, 6, 8 

### LINKED ISSUE #1: Also generate -meta files for map.
All information for generating the meta files found in https://github.com/simra-project/simra-project.github.io/tree/master/region is available when running osmColoring. Thus, they should also be generated here based on the input parameters for each region.

### PR DESCRIPTION
**Pull request by MeerkatPerson**
Deleted old pull request to avoid conflict described in #8. Presenting this new one instead.

Fixes #1, #2, #3, #6, #8.
1. added function 'toMetaFile()' to CommandLineArguments.kt, call this function in Main.kt. Write the resultant meta files to output_data (#1 ).
2. Ensured the deleteCharAt(geoJSONContent.length()-3) operation in line 164 of SegmentMapper.java is only called if geoJSONContent.length() > 3. Tested with Alzey ride data pulled from VM2 (#2 ). 
3. To deal with highwaylanes occasionally being separated by "," instead of ", " replace all ", " with "," and then split by "," . Tested with Karlsruhe region (#3 ).
6. Added extensive documentation (#6 ).
8. Name of json data output file is now different depending on (minRides == 1). Likewise, a different meta file is produced depending on (minRides == 1) (#8 ).

Additional changes:
- Put .gitkeep files into the three data directories (simra_data, osm_data, output_data) so new users don't have to create these directories themselves.

Additional changes:
- Sorry about the amount of issues included in this PR, will stick to more incremental PRs in the future 🐒

### CODE REVIEW

**Comment by MoeweX** [comment]
I do not like the idea of having a second "local visualization" folder. By doing this, we have to maintain and test changes at two locations.
Also, I do not see why this should be necessary at all. The simra-project.github.io repository is also open source, thus, everybody can clone it. Then, simply starting a Webserver, e.g., with `python3 -m http.server 8000`, is sufficient to host the map locally.
I would prefer to better highlight this feature rather than having duplicated code that must be maintained.

Also, I would prefer it if we had different PR for different issues, at least if they are not related to each other.

**Comment by MeerkatPerson** [comment]
local_visualization has been removed and detailed instructions on how to use the project website as a submodule for map visualization have been added.

**Review by MoeweX — APPROVED** [review]
Perfect, thanks!

**Comment by MoeweX** [comment]
When @selphiron approved this PR, please merge with "squash and merge"

**Review by selphiron — APPROVED** [review]

**Pull request merged**
